<a href="https://colab.research.google.com/github/VijayRameshkumar/AI_Curriculum/blob/master/00_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [10]:
# cpu  - cpu
# cuda - gpu

is_gpu = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float, device=is_gpu, requires_grad=True)

print(f"tensor shape :\n\t{tensor.shape}\ntensor is : \n\t{tensor}")

tensor shape :
	torch.Size([2, 3])
tensor is : 
	tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


## 1. Method to create tensors

In [30]:
print(torch.empty((3, 2)), end="\n\n")
print(torch.zeros((3, 2)), end="\n\n")
print(torch.ones((3, 2)), end="\n\n")
print(torch.eye(3, 3), end="\n\n")
print(torch.arange(1, 10, 1).reshape(3, 3), end="\n\n")
print(torch.linspace(start=0.1, end=1, steps=10), end="\n\n")
print(torch.empty((3, 3)).normal_(mean=0, std=1), end="\n\n")
print(torch.empty((3, 3)).uniform_(0, 1), end="\n\n")
print(torch.diag((torch.ones(3, 3))), end="\n\n") # fetch diagonal Values

tensor([[-2.1320e-28,  3.0920e-41],
        [ 3.3631e-44,  0.0000e+00],
        [        nan,  0.0000e+00]])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

tensor([[ 0.6166, -0.4784,  0.0967],
        [-0.0667,  1.3739, -0.2398],
        [-1.5992, -0.3194, -0.0947]])

tensor([[0.6250, 0.6092, 0.9170],
        [0.7165, 0.2615, 0.9060],
        [0.8850, 0.9479, 0.5150]])

tensor([1., 1., 1.])



## 2. Convert tensor into other types

In [32]:
tensor = torch.arange(1, 11, 1)
print(tensor.bool(), end='\n')
print(tensor.short(), end='\n')
print(tensor.half(), end='\n')
print(tensor.long(), end='\n')
print(tensor.float(), end='\n')
print(tensor.double(), end='\n')

tensor([True, True, True, True, True, True, True, True, True, True])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int16)
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float16)
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


In [34]:
import numpy as np

np_array = np.zeros((3, 3))
tensor = torch.from_numpy(np_array)
print(f"tensor : {tensor}\n")

tensor = tensor.numpy()
print(f"numpy : {tensor}")

tensor : tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

numpy : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##3. Tensor Math & Comaparision operation

In [41]:
x = torch.tensor([[1, 2, 3], [1, 2, 3]])
y = torch.tensor([[4, 5, 6], [4, 5, 6]])

################################################
z1 = torch.empty((2, 3))
print(f"Z1 before addition : {z1}")
torch.add(x, y, out=z1)
print(f"Z1 after addition : {z1}\n\n")

z1 = torch.empty((2, 3))
print(f"Z1 before addition : {z1}")
z1 = x + y
print(f"Z1 after addition : {z1}\n\n")

################################################
z1 = torch.empty((2, 3))
print(f"Z1 before subtraction : {z1}")
torch.sub(x, y, out=z1)
print(f"Z1 after subtraction : {z1}\n\n")

z1 = torch.empty((2, 3))
print(f"Z1 before subtraction : {z1}")
z1 = x - y
print(f"Z1 after subtraction : {z1}\n\n")

################################################
z1 = torch.empty((2, 3))
print(f"Z1 before division : {z1}")
torch.div(x, y, out=z1)
print(f"Z1 after division : {z1}\n\n")
torch.true_divide(x, y, out=z1)
print(f"Z1 after division : {z1}\n\n")

z1 = torch.empty((2, 3))
print(f"Z1 before division : {z1}")
z1 = x / y
print(f"Z1 after division : {z1}\n\n")


Z1 before addition : tensor([[-2.8071e-28,  3.0920e-41,  7.0065e-45],
        [ 0.0000e+00,  8.4078e-45,  0.0000e+00]])
Z1 after addition : tensor([[5., 7., 9.],
        [5., 7., 9.]])


Z1 before addition : tensor([[-2.8075e-28,  3.0920e-41,  7.0065e-45],
        [ 8.4078e-45,  4.0000e-01,  5.0000e-01]])
Z1 after addition : tensor([[5, 7, 9],
        [5, 7, 9]])


Z1 before subtraction : tensor([[-2.8069e-28,  3.0920e-41,  7.0065e-45],
        [ 8.4078e-45,  4.0000e-01,  5.0000e-01]])
Z1 after subtraction : tensor([[-3., -3., -3.],
        [-3., -3., -3.]])


Z1 before subtraction : tensor([[-2.8075e-28,  3.0920e-41,  7.0065e-45],
        [ 8.4078e-45,  4.0000e-01,  5.0000e-01]])
Z1 after subtraction : tensor([[-3, -3, -3],
        [-3, -3, -3]])


Z1 before division : tensor([[-2.8071e-28,  3.0920e-41,  7.0065e-45],
        [ 8.4078e-45,  4.0000e-01,  5.0000e-01]])
Z1 after division : tensor([[0.2500, 0.4000, 0.5000],
        [0.2500, 0.4000, 0.5000]])


Z1 after division : tensor([[

In [43]:
## inplace operations

x = torch.tensor([[1, 2, 3], [1, 2, 3]])
t = torch.zeros((2, 3))

print(f" before inplace addition {t}")
t.add_(x)
print(f" after inplace addition {t}\n\n")

x = torch.tensor([[1, 2, 3], [1, 2, 3]])
t = torch.zeros((2, 3))

print(f" before inplace addition {t}")
t += x
print(f" after inplace addition {t}")

 before inplace addition tensor([[0., 0., 0.],
        [0., 0., 0.]])
 after inplace addition tensor([[1., 2., 3.],
        [1., 2., 3.]])


 before inplace addition tensor([[0., 0., 0.],
        [0., 0., 0.]])
 after inplace addition tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [51]:
## basic tensor methods
print(f"exponential {x.pow(2)}")
print(f"exponential {x**2}\n\n")

## simple comparison
print(f"comparison {x>1}") ##boolean
print(f"comparison {(x>1).type(torch.uint8)}") ##booleann to int

exponential tensor([[1, 4, 9],
        [1, 4, 9]])
exponential tensor([[1, 4, 9],
        [1, 4, 9]])


comparison tensor([[False,  True,  True],
        [False,  True,  True]])
comparison tensor([[0, 1, 1],
        [0, 1, 1]], dtype=torch.uint8)


In [54]:
## matrix multiplication

x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

print(f"matrix multiplication {torch.mm(x1, x2)}\n\n")
print(f"matrix multiplication {x1.mm(x2)}\n\n")

matrix multiplication tensor([[1.1779, 1.1450, 1.1844],
        [1.2931, 1.2562, 1.3766]])


matrix multiplication tensor([[1.1779, 1.1450, 1.1844],
        [1.2931, 1.2562, 1.3766]])




In [79]:
##matrix exponential multiplication
x1 = sum([torch.ones((3, 3)) for i in range(1)])

print(x1) 
x1.matrix_power(6)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[243., 243., 243.],
        [243., 243., 243.],
        [243., 243., 243.]])

In [90]:
## element wise multiplication

x = torch.tensor([[1, 2, 3], [1, 2, 3]])
y = torch.tensor([[4, 5, 6], [4, 5, 6]])

print(f"element wise mul : {x*y} \n\n")
z = x*y

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(f"dot product : {torch.dot(x, y)} \n\n")

element wise mul : tensor([[ 4, 10, 18],
        [ 4, 10, 18]]) 


dot product : 32 




In [92]:
## batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)

print(tensor1.shape, tensor2.shape, out_bmm.shape)

torch.Size([32, 10, 20]) torch.Size([32, 20, 30]) torch.Size([32, 10, 30])


In [95]:
#Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

print(x1, x2)

z = x1-x2
print(z, z.shape)

z = x1**x2
print(z, z.shape)

tensor([[0.8221, 0.5668, 0.7983, 0.6125, 0.6381],
        [0.7611, 0.9641, 0.1298, 0.1610, 0.9584],
        [0.1787, 0.6036, 0.0366, 0.9463, 0.1288],
        [0.2189, 0.6480, 0.0283, 0.6905, 0.3988],
        [0.1277, 0.7695, 0.4759, 0.2765, 0.9941]]) tensor([[0.9255, 0.0976, 0.6284, 0.1711, 0.9822]])
tensor([[-0.1034,  0.4691,  0.1699,  0.4414, -0.3441],
        [-0.1644,  0.8664, -0.4986, -0.0101, -0.0239],
        [-0.7468,  0.5060, -0.5918,  0.7752, -0.8535],
        [-0.7067,  0.5503, -0.6001,  0.5194, -0.5834],
        [-0.7978,  0.6718, -0.1525,  0.1054,  0.0119]]) torch.Size([5, 5])
tensor([[0.8342, 0.9461, 0.8680, 0.9195, 0.6432],
        [0.7768, 0.9964, 0.2772, 0.7316, 0.9591],
        [0.2032, 0.9519, 0.1252, 0.9906, 0.1336],
        [0.2451, 0.9585, 0.1064, 0.9386, 0.4054],
        [0.1488, 0.9747, 0.6271, 0.8026, 0.9942]]) torch.Size([5, 5])


In [110]:
# Other usefull tensor operations
x = torch.tensor([[1, 2, 3], [1, 2, 3]])
y = torch.tensor([[4, 5, 6], [4, 5, 6]])

sum_x = torch.sum(x)
print(f"sum : {sum_x}")

values, indices = torch.max(x, dim=0)
print(f"max : \t values{values} \t indices{indices}")

values, indices = torch.min(x, dim=0)
print(f"min : \t values{values} \t indices{indices}")

abs_x = torch.abs(x)
print(f"absolute x {abs_x}")

z = torch.argmax(x, dim=0)
print(f"argmax : {z}")

z = torch.argmin(x, dim=0)
print(f"argmin : {z}")

mean_x = torch.mean(x.float(), dim=0)
print(f"mean : {mean_x}")

z = torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]])) #compare equal (x & y)
print(f"eq : {z}")

y = torch.tensor([[4, 5, 6], [2, 1, 3]])
sorted_y, indices = torch.sort(y, dim=1, descending=False)

print(f"sorted y {sorted_y}, indices {indices}\n\n")
print(f"clamping {torch.clamp(sorted_y, min=2)}\n")
print(f"Binary to bool from [1, 0, 0, 1, 0, 1, 1, 1] to: {torch.tensor([1, 0, 0, 1, 0, 1, 1, 1], dtype=torch.bool)}\n")
print(f"if any non-null : {torch.any(x)} \n")
print(f"if all is not null : {torch.all(x)} \n")

print()

sum : 12
max : 	 valuestensor([1, 2, 3]) 	 indicestensor([0, 0, 0])
min : 	 valuestensor([1, 2, 3]) 	 indicestensor([0, 0, 0])
absolute x tensor([[1, 2, 3],
        [1, 2, 3]])
argmax : tensor([0, 0, 0])
argmin : tensor([0, 0, 0])
mean : tensor([1., 2., 3.])
eq : tensor([[ True, False],
        [False,  True]])
sorted y tensor([[4, 5, 6],
        [1, 2, 3]]), indices tensor([[0, 1, 2],
        [1, 0, 2]])


clamping tensor([[4, 5, 6],
        [2, 2, 3]])
Binary to bool from [1, 0, 0, 1, 0, 1, 1, 1] to: tensor([ True, False, False,  True, False,  True,  True,  True]) 

if any non null : True
if any null : True


In [114]:
## tensor Indexing

batch_size = 10
features = 25

x = torch.rand(batch_size, features)

print(f"first row shape : {x[0].shape}")
print(f"first column shape {x[:, 0].shape}")
print(f"second row & first 10 column shape {x[:, 0].shape}")

x.shape

first row shape : torch.Size([25])
first column shape torch.Size([10])
second row & first 10 column shape torch.Size([10])


torch.Size([10, 25])

In [133]:
## fancy Indexing
x = torch.rand((3, 5))

rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

print(x[rows, cols])

## Advanced Indexing
x = torch.arange(10)

print(x[(x < 2) | (x>8)])
print(x[x.remainder(2) == 0])
print(torch.where(x>5, x, x*2)) # Xi if condition else Yi
print(x.ndimension())
print(torch.tensor([1, 0, 3, 0, 5, 3]).unique())
print(x.numel())

tensor([0.5159, 0.4862])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
1
tensor([0, 1, 3, 5])
10


In [144]:
## Tesnor reshape
x = torch.arange(9)

print(x.view(3, 3))
print(x.reshape(3, 3))

print(x.reshape(3, 3).t().contiguous().view(9))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [147]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(x1)
print(x2)

print(torch.cat((x1, x2), dim=0))
print(torch.cat((x1, x2), dim=1))

tensor([[0.5677, 0.3140, 0.8823, 0.2427, 0.7123],
        [0.2462, 0.9608, 0.8551, 0.5385, 0.4715]])
tensor([[0.1025, 0.3296, 0.1893, 0.9629, 0.4924],
        [0.4794, 0.7865, 0.4595, 0.4603, 0.6206]])
tensor([[0.5677, 0.3140, 0.8823, 0.2427, 0.7123],
        [0.2462, 0.9608, 0.8551, 0.5385, 0.4715],
        [0.1025, 0.3296, 0.1893, 0.9629, 0.4924],
        [0.4794, 0.7865, 0.4595, 0.4603, 0.6206]])
tensor([[0.5677, 0.3140, 0.8823, 0.2427, 0.7123, 0.1025, 0.3296, 0.1893, 0.9629,
         0.4924],
        [0.2462, 0.9608, 0.8551, 0.5385, 0.4715, 0.4794, 0.7865, 0.4595, 0.4603,
         0.6206]])


In [152]:
batch = 64

x = torch.rand((batch, 2, 5))
print(x.shape)
z = x.view(batch, -1)
print(z.shape)
z = x.permute(0, 2, 1) # trnsposing on multi dimensional case
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])
torch.Size([64, 5, 2])


In [167]:
x = torch.arange(10)
print(x)
print(x.squeeze())
print(x.unsqueeze(0))
print(x.unsqueeze(1))

print(x.unsqueeze(0).unsqueeze(1)) # 1x1x10 matrix

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
